Handy addPath function

diff --git a/zshrc-base b/zshrc-base
--- a/zshrc-base
+++ b/zshrc-base
@@ -18,4 +18,21 @@ export CLICOLOR=1
 
 alias ls="ls -lhG"
 
+addPath() {
+    position="end"
+    newPart="$1"
+    if ! [ "$2" == "" ]; then
+        position="$2"
+    fi
+    if ! [ "$position" == "end" ] && ! [ "$position" == "start" ]; then
+        echo "WARNING: invalid path position $position, adding to end"
+        position="end"
+    fi
+    if [ "$position" == "end" ]; then
+        PATH="$PATH:$newPart"
+    elif [ "$position" == "start" ]; then
+        PATH="$newPart:$PATH"
+    fi
+}
+
 PATH=$HOME/Scripts:$PATH
